version: '3.8'

services:
  postgres:
    image: postgres:12-alpine
    env_file: .env
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      # POSTGRES_INITDB_ARGS: $POSTGRES_INITDB_ARGS
      # POSTGRES_INITDB_WALDIR: $POSTGRES_INITDB_WALDIR
      # POSTGRES_HOST_AUTH_METHOD: $POSTGRES_HOST_AUTH_METHOD
    ports:
      - 5432:5432
    volumes:
      - pgdb:/var/lib/postgresql/data
    restart: always

volumes:
  pgdb: